### ISSUE TITLE
Last question is bugged

### ISSUE THREAD

**Issue by mattgahrns** [learn-co-curriculum/ruby-oo-introduction-quiz#2]
When answering the 2nd to last question the last question becomes greyed out and unanswerable.
<img width="729" alt="Screen Shot 2019-10-08 at 4 03 41 PM" src="https://user-images.githubusercontent.com/25352997/66439666-3fe0f200-e9e5-11e9-83fe-c61c2b2c09c6.png">

**Comment by rrcobb** [comment]
We've updated this since this was opened, and can't reproduce the error. If you (or anyone else who sees this issue) is still experiencing this, reopen and let us know. 

Thanks for taking the time to report!
