### ISSUE TITLE
#10 is incorrect

### ISSUE THREAD

**Issue by alyon4a** [learn-co-curriculum/ruby-oo-introduction-quiz#5]
there's no 'initialize' method in Pet class example, so it shouldn't be able to create new instance with a name parameter, there should be an Argument Error

**Comment by maxwellbenton** [comment]
Hi @alyon4a,

Thank you for spotting this and providing this feedback. We've updated this quiz and added an `initialize` method to the example. The quiz answers should now be valid.

Thank you for contributing!
