### ISSUE TITLE
Question 6 Correct Answer Not Available

### ISSUE THREAD

**Issue by tylergreason** [learn-co-curriculum/ruby-oo-introduction-quiz#6]
Question 6's correct answer is 'NoMethodError', not 'ArgumentError'.

**Comment by rrcobb** [comment]
Hi @tylergreason ! Thanks for submitting the issue.

I couldn't replicate the issue in irb - I get an ArgumentError, like the quiz suggests:
```
> rabbit.name("Chokola")
Traceback (most recent call last):
        5: from /usr/bin/irb:23:in `<main>'
        4: from /usr/bin/irb:23:in `load'
        3: from /Library/Ruby/Gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        2: from (irb):11
        1: from (irb):6:in `name'
ArgumentError (wrong number of arguments (given 1, expected 0))
```

I'm going to close for now, but if you have reproduction steps, please go ahead and reopen the issue!
